# @PydevCodeAnalysisIgnore
import unittest

from test.integrationTest.BaseStationCanSendCommandTest import BaseStationCanSendCommandTest
from test.integrationTest.RobotCanSendCommandTest import RobotCanSendCommandTest
from test.stateUnitTest import HasNoPuckStateTest
from test.stateUnitTest import HasPuckStateTest
from test.stateUnitTest import HasReadLetterBoardStateTest
from test.stateUnitTest import HasReadOrientationBoardStateTest
from test.stateUnitTest import HasReadResistanceStateTest
from test.stateUnitTest import NearLetterBoardStateTest
from test.stateUnitTest import NearGoalPositionStateTest
from test.stateUnitTest import NearOrientationBoardStateTest
from test.stateUnitTest import NearPucksStateTest
from test.stateUnitTest import NearResistanceStateTest
from test.stateUnitTest import NoResistanceValueStateTest
from test.unitTest.ElectromagnetTest import ElectromagnetTest
from test.unitTest.PositionTest import PositionTest
from test.unitTest.PuckTest import PuckTest
from test.unitTest import GameTest
from test.unitTest import MapTest
from test.unitTest import RobotTest


